### PR TITLE
added alt attribute to img tags

### PR DESCRIPTION
**Pull request by tbenz9**
The "alt" attribute is technically required in the  tag.  This PR adds an "alt" attribute to all img tags.  This is one of the main offenders in the Obelisk.tech failing HTML lint.

See link for reference: https://www.w3schools.com/tags/att_img_alt.asp

### CODE REVIEW

**Comment by zachherbert** [comment]
@tbenz9 we made a couple changes since your PR, could you update and we will merge today?

**Comment by tbenz9** [comment]
I'm a little confused.  I Clicked "Resolve conflicts" and fixed the conflicts but it's still showing that it has 2 Conflicting files.  Maybe I don't have permission to resolve conflicts via the web interface?  Are they still showing up as conflicting for you?

**Comment by tbenz9** [comment]
I went back and fixed the merge conflicts in the fork and committed.  That seems to have worked, I'll go study up on my Git rebasing so I don't make this mistake again.

**Comment by zachherbert** [comment]
Thanks @tbenz9!

**Pull request merged**
